### PR TITLE
Feature: Streaming Reply

### PR DESCRIPTION
**Pull request by Sponge-bink**
Streaming Reply now appears as an option to stream the reply to you while it being generated, defaulted to unchecked. I also added a little touch that let ChatFred tell you in the subtitle which model you are talking to.

### CODE REVIEW

**Comment by Sponge-bink** [comment]
This PR is now ready for review.

**Comment by Sponge-bink** [comment]
The check failed probably because `pdb` is imported, not sure why tho.

I ran pre-commit locally and found some .so files in the newly introduced dependancies, that seems to be not allowed but the bot here didn't report any issue on that. My local result showed that the debug statements check passed too…

**Comment by chrislemke** [comment]
Wow! Thanks! That is quite a thing. Could you please run [detect_banned_file_types.sh](xhttps://github.com/chrislemke/ChatFred/blob/main/scripts/detect_banned_file_types.sh) to make sure no files are included which are "banned" by Alfred? Cheers!

**Comment by Sponge-bink** [comment]
> Wow! Thanks! That is quite a thing. Could you please run [detect_banned_file_types.sh](https://github.com/chrislemke/ChatFred/blob/main/scripts/detect_banned_file_types.sh) to make sure no files are included which are "banned" by Alfred? Cheers!

Unfortunately there are "banned" files introduced in this PR:

```
Found .so file(s):
./workflow/src/libs/markupsafe/_speedups.cpython-310-darwin.so
./workflow/src/libs/websockets/speedups.cpython-310-darwin.so
./workflow/src/libs/yaml/_yaml.cpython-310-darwin.so
./workflow/src/libs/pydantic/annotated_types.cpython-310-darwin.so
./workflow/src/libs/pydantic/color.cpython-310-darwin.so
./workflow/src/libs/pydantic/_hypothesis_plugin.cpython-310-darwin.so
./workflow/src/libs/pydantic/config.cpython-310-darwin.so
./workflow/src/libs/pydantic/types.cpython-310-darwin.so
./workflow/src/libs/pydantic/tools.cpython-310-darwin.so
./workflow/src/libs/pydantic/schema.cpython-310-darwin.so
./workflow/src/libs/pydantic/parse.cpython-310-darwin.so
./workflow/src/libs/pydantic/dataclasses.cpython-310-darwin.so
./workflow/src/libs/pydantic/json.cpython-310-darwin.so
./workflow/src/libs/pydantic/decorator.cpython-310-darwin.so
./workflow/src/libs/pydantic/errors.cpython-310-darwin.so
./workflow/src/libs/pydantic/class_validators.cpython-310-darwin.so
./workflow/src/libs/pydantic/__init__.cpython-310-darwin.so
./workflow/src/libs/pydantic/typing.cpython-310-darwin.so
./workflow/src/libs/pydantic/datetime_parse.cpython-310-darwin.so
./workflow/src/libs/pydantic/error_wrappers.cpython-310-darwin.so
./workflow/src/libs/pydantic/env_settings.cpython-310-darwin.so
./workflow/src/libs/pydantic/networks.cpython-310-darwin.so
./workflow/src/libs/pydantic/version.cpython-310-darwin.so
./workflow/src/libs/pydantic/fields.cpython-310-darwin.so
./workflow/src/libs/pydantic/main.cpython-310-darwin.so
./workflow/src/libs/pydantic/utils.cpython-310-darwin.so
./workflow/src/libs/pydantic/validators.cpython-310-darwin.so
./workflow/src/libs/pydantic/mypy.cpython-310-darwin.so
```

That's quite a lot… Is it possible to work this around?

**Comment by chrislemke** [comment]
> > Wow! Thanks! That is quite a thing. Could you please run [detect_banned_file_types.sh](https://github.com/chrislemke/ChatFred/blob/main/scripts/detect_banned_file_types.sh) to make sure no files are included which are "banned" by Alfred? Cheers!
> 
> Unfortunately there are "banned" files introduced in this PR:
> 
> ```
> Found .so file(s):
> ./workflow/src/libs/markupsafe/_speedups.cpython-310-darwin.so
> ./workflow/src/libs/websockets/speedups.cpython-310-darwin.so
> ./workflow/src/libs/yaml/_yaml.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/annotated_types.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/color.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/_hypothesis_plugin.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/config.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/types.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/tools.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/schema.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/parse.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/dataclasses.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/json.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/decorator.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/errors.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/class_validators.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/__init__.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/typing.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/datetime_parse.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/error_wrappers.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/env_settings.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/networks.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/version.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/fields.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/main.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/utils.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/validators.cpython-310-darwin.so
> ./workflow/src/libs/pydantic/mypy.cpython-310-darwin.so
> ```
> 
> That's quite a lot… Is it possible to work this around?

Hmm, maybe those files are actually not necessary. Maybe you can check to remove them? 

Additionally, it is important that the workflow does not exceed a certain size.

**Comment by Sponge-bink** [comment]
> Hmm, maybe those files are actually not necessary.

You are right! 👍 I removed all .so files and the workflow functions as normal. 

But the debug statements check still failed despite the same check got skipped on my machine.

> Additionally, it is important that the workflow does not exceed a certain size.

Which is? I didn't see such thing [here](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/).

**Comment by chrislemke** [comment]
Concerning the size. I could not find it in the docs - but some guy told me once I was publishing ChatFred for the first time. Anyhow let's try. I will merge your improvements.
Thanks for the great improvements.

**Comment by Sponge-bink** [comment]
> Maybe you want to add something to the readme file?

Seems like I did that only for the GitHub readme file. Should I create another PR or if it's ok you can copy it from there 😅

Or here:

- **Stream reply**: If checked, partial message deltas will be sent, like in ChatGPT. Reply will be shown in a stand-alone window implemented using [Flet](https://flet.dev). Close it by pressing Esc. Default: `off`. Overrides `Show ChatGPT is thinking message` when checked.

**Comment by chrislemke** [comment]
> > Maybe you want to add something to the readme file?
> 
> Seems like I did that only for the GitHub readme file. Should I create another PR or if it's ok you can copy it from there 😅
> 
> Or here:
> 
> * **Stream reply**: If checked, partial message deltas will be sent, like in ChatGPT. Reply will be shown in a stand-alone window implemented using [Flet](https://flet.dev). Close it by pressing Esc. Default: `off`. Overrides `Show ChatGPT is thinking message` when checked.

Just copy it. :-)

**Comment by Sponge-bink** [comment]
> Just copy it. :-)

Updated ;)

**Comment by vitorgalvao** [comment]
This *considerably* increases the size of the workflow, from almost 6MB to over 42MB! Is all of it necessary? Isn’t there an alternative to make it less disruptive?

Also, are there screenshots/examples of how this works/what it looks like in practice?

**Comment by Sponge-bink** [comment]
> from almost 6MB to over 42MB!

Yeah, considering Flet is a cross platform tool.

> Is all of it necessary?

Maybe not… I deleted the installation of Flet, installed it again with the largest file `/src/libs/flet/bin/flet-macos-amd64.tar.gz` deleted and the workflow ran normally. Maybe that file should be gone. 

> Is there an alternative to make it less disruptive?

I wondered and am still wondering the same question. Would be great if this was macOS native. And can be updated from inside the script. 

> Also, are there screenshots/examples of how this works/what it looks like in practice?

#93

**Comment by chrislemke** [comment]
Hey @vitorgalvao!
I just checked if we could remove some more files. After some cleanup. The workflow has 21,6 MB. That is a bit better but, still not close to 6 MB. What do you think?

**Pull request merged**
